### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by yuweibao15** [bardin-lab/readtagger#560]
Thank you very much for this tool! I am following the paper _Evolution and genomic signatures of spontaneous
somatic mutation in Drosophila intestinal stem cells_ , which used readtagger in preparing fastqs.

I tried to install it in two ways:

1. **pip install readtagger**
After installation, I ran **readtagger -h** but have the following error:

>>>>
Traceback (most recent call last):
  File "/home/ybao2/anaconda3/bin/readtagger", line 5, in <module>
    from readtagger.cli.readtagger_cli import readtagger
  File "/home/ybao2/anaconda3/lib/python3.9/site-packages/readtagger/cli/readtagger_cli.py", line 4, in <module>
    from readtagger.readtagger import TagManager
  File "/home/ybao2/anaconda3/lib/python3.9/site-packages/readtagger/readtagger.py", line 8, in <module>
    from .allow_dovetailing import (
  File "/home/ybao2/anaconda3/lib/python3.9/site-packages/readtagger/allow_dovetailing.py", line 5, in <module>
    from .bam_io import BamAlignmentWriter as Writer
  File "/home/ybao2/anaconda3/lib/python3.9/site-packages/readtagger/bam_io.py", line 7, in <module>
    import compare_reads
  File "/home/ybao2/anaconda3/lib/python3.9/site-packages/compare_reads/__init__.py", line 6, in <module>
    from ._compare_reads import (  # noqa
  File ".tox/py36/lib/python3.6/site-packages/pysam/libcalignmentfile.pxd", line 61, in init compare_reads._compare_reads
AttributeError: module 'pysam.libcalignmentfile' has no attribute 'PileupColumn'
>>>>

2. I also tried **conda install -c mvdbeek readtagger** using both python version 3.6, 3.8 and 3.9, but failed due to glibc conflict. Is there a specific python version I should use?
>>>>>
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
>>>>>>

Please let me know your advice on resolving this issue.

Thank you very much for your help!

**Comment by yuweibao15** [comment]
For future reference, this issue can be solved by doing the following:
1. Create a conda environment. 
2. Install `https://github.com/bardin-lab/readtagger/blob/master/requirements.txt` in the new conda environment.
3. Then do `pip install readtagger`
